[package]
name = "cse_local_give"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssh2 = "0.9.3"
subprocess = "0.2.9"
rand = "0.8.5"
xdg = "2.4.1"